ERROR2023-05-17 09:32:27,305D:\Project\jieren_test\Merchant_Api_Test\logs\error-2023-05-17.log:mysql_control.py:142 数据库连接失败，失败原因 tuple index out of range
ERROR2023-05-17 09:33:59,623D:\Project\jieren_test\Merchant_Api_Test\logs\error-2023-05-17.log:mysql_control.py:142 数据库连接失败，失败原因 tuple index out of range
ERROR2023-05-17 09:35:22,161D:\Project\jieren_test\Merchant_Api_Test\logs\error-2023-05-17.log:assertion_control.py:165 JsonPath值获取失败 $.data.cashierName 
ERROR2023-05-17 09:39:58,214D:\Project\jieren_test\Merchant_Api_Test\logs\error-2023-05-17.log:assertion_control.py:165 JsonPath值获取失败 $.data.cashierName 
ERROR2023-05-17 09:45:18,297D:\Project\jieren_test\Merchant_Api_Test\logs\error-2023-05-17.log:assertion_control.py:165 JsonPath值获取失败 $.data.cashierName 
ERROR2023-05-17 10:02:14,704D:\Project\jieren_test\Merchant_Api_Test\logs\error-2023-05-17.log:assertion_control.py:165 JsonPath值获取失败 $.data[0].cashierName 
ERROR2023-05-17 10:44:00,517D:\Project\jieren_test\Merchant_Api_Test\logs\error-2023-05-17.log:assertion_control.py:165 JsonPath值获取失败 $.data[0].cashierName 
ERROR2023-05-17 10:58:30,584D:\Project\jieren_test\Merchant_Api_Test\logs\error-2023-05-17.log:assertion_control.py:165 JsonPath值获取失败 $.data[0].actualAmount 
ERROR2023-05-17 14:38:59,654D:\Project\jieren_test\Merchant_Api_Test\logs\error-2023-05-17.log:assertion_control.py:165 JsonPath值获取失败 $.data.actualAmount 
ERROR2023-05-17 14:42:55,358D:\Project\jieren_test\Merchant_Api_Test\logs\error-2023-05-17.log:mysql_control.py:142 数据库连接失败，失败原因 (1046, 'No database selected')
ERROR2023-05-17 14:43:23,626D:\Project\jieren_test\Merchant_Api_Test\logs\error-2023-05-17.log:assertion_control.py:165 JsonPath值获取失败 $.data.actualAmount 
ERROR2023-05-17 14:44:29,120D:\Project\jieren_test\Merchant_Api_Test\logs\error-2023-05-17.log:assertion_control.py:165 JsonPath值获取失败 $.data.actualAmount 
ERROR2023-05-17 14:46:36,920D:\Project\jieren_test\Merchant_Api_Test\logs\error-2023-05-17.log:mysql_control.py:142 数据库连接失败，失败原因 (1046, 'No database selected')
ERROR2023-05-17 14:48:04,574D:\Project\jieren_test\Merchant_Api_Test\logs\error-2023-05-17.log:mysql_control.py:142 数据库连接失败，失败原因 tuple index out of range
ERROR2023-05-17 14:54:54,859D:\Project\jieren_test\Merchant_Api_Test\logs\error-2023-05-17.log:mysql_control.py:142 数据库连接失败，失败原因 'bool' object is not subscriptable
ERROR2023-05-17 15:36:41,064D:\Project\jieren_test\Merchant_Api_Test\logs\error-2023-05-17.log:mysql_control.py:142 数据库连接失败，失败原因 'bool' object is not subscriptable
ERROR2023-05-17 15:41:28,940D:\Project\jieren_test\Merchant_Api_Test\logs\error-2023-05-17.log:mysql_control.py:142 数据库连接失败，失败原因 'bool' object is not subscriptable
ERROR2023-05-17 15:44:41,553D:\Project\jieren_test\Merchant_Api_Test\logs\error-2023-05-17.log:mysql_control.py:142 数据库连接失败，失败原因 'bool' object is not subscriptable
ERROR2023-05-17 15:45:41,392D:\Project\jieren_test\Merchant_Api_Test\logs\error-2023-05-17.log:mysql_control.py:142 数据库连接失败，失败原因 'bool' object is not subscriptable
ERROR2023-05-17 15:46:12,743D:\Project\jieren_test\Merchant_Api_Test\logs\error-2023-05-17.log:mysql_control.py:142 数据库连接失败，失败原因 (1064, "You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '` ='None'' at line 1")
ERROR2023-05-17 15:47:30,226D:\Project\jieren_test\Merchant_Api_Test\logs\error-2023-05-17.log:mysql_control.py:142 数据库连接失败，失败原因 tuple index out of range
ERROR2023-05-17 15:48:00,356D:\Project\jieren_test\Merchant_Api_Test\logs\error-2023-05-17.log:mysql_control.py:142 数据库连接失败，失败原因 'bool' object is not subscriptable
ERROR2023-05-17 17:51:32,979D:\Project\jieren_test\Merchant_Api_Test\logs\error-2023-05-17.log:mysql_control.py:142 数据库连接失败，失败原因 (1064, 'You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near \'"2023-05-17%“ ORDER BY create_time DESC\' at line 1')
